---
version: '3'
services:

# START SERVICE backup.external
  backup:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.backup.external:20200419
    environment: []
    command: [${CONTECO_DC_BACKUP_COMMAND}]
    volumes: [${CONTECO_DC_BACKUP_VOLUMES}]
    ports: []
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: ${CONTECO_DC_BACKUP_DEPLOY_MODE}
      resources:
        limits:
          cpus: '${CONTECO_DC_BACKUP_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_BACKUP_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_BACKUP_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_BACKUP_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      labels: [${CONTECO_DC_BACKUP_DEPLOY_LABELS}]
# END SERVICE backup.external

volumes: {}
networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
